### ISSUE TITLE
IF does not support truth-y values

### ISSUE THREAD

**Issue by prescod** [WebsiteHQ/formula#12]
In Excel and Google Sheets, the third argument is optional.

**Comment by jcfisher007** [comment]
The IF function is defined in the functionfoundry project. It is called branch since if is already a reserved keyword in javascript.

The third argument should be optional. If it is omitted and the first argument is false then the function should return undefined.

Test case:
https://github.com/WebsiteHQ/functionfoundry/blob/master/test/branch.js

What issue are you facing?

**Comment by prescod** [comment]
I think I was confused between this project and the formulapages version.

But what should be the output of this:

> formula.compile("if(6,2)")()
undefined

Shouldn't it be "2" because 6 is truth-y?

**Comment by jcfisher007** [comment]
The current implementation of branch is strict and only accepts true values.

I checked in Google sheets and it does accept truth-y values. Currently the goal isn't to clone the exact spec of google sheets but perhaps accepting truth-y values would be preferable.

**Comment by jcfisher007** [comment]
Filed an issue under the related project. The next release of this project will include an updated dependency.

https://github.com/WebsiteHQ/functionfoundry/issues/25

**Comment by jcfisher007** [comment]
Fixed in https://github.com/WebsiteHQ/formula/commit/188c394b77af6e9aa5640716b938009893befdf2
